//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/InputSystem/MechanicsControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MechanicsControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MechanicsControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MechanicsControls"",
    ""maps"": [
        {
            ""name"": ""Pirouette"",
            ""id"": ""c0692518-3311-45cb-8251-6006babdc658"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""99ff6766-6bd9-4ba8-8008-113b69d1f2a4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PressX"",
                    ""type"": ""Button"",
                    ""id"": ""9869c433-7617-4cf8-b072-8307eb0b6190"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PressY"",
                    ""type"": ""Button"",
                    ""id"": ""7812a473-d6ff-46f3-b683-0cccfcfc3a6d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PressA"",
                    ""type"": ""Button"",
                    ""id"": ""bd87e157-9607-4be3-befd-0282a74b750d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PressB"",
                    ""type"": ""Button"",
                    ""id"": ""2f415f7a-e6a3-4d7c-aee3-566bdaab73a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""8e6b204c-a566-4a85-b801-c44c775b056b"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""00a5509d-498e-4677-ba42-5f1d8ed7e5b7"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f7535227-c40b-4a17-b792-fd7982c1d0a6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""82120446-e74a-451f-9d07-7117305b32d2"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""05998252-c352-4275-ba73-2d6d78646d19"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d64375d5-ca0a-44a8-8a64-a27597500c6f"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3a709b30-7786-4841-9e52-4b7e82ab763b"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""cc02dafd-c4a9-4ba8-9728-93c30b44d8d6"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""61449690-1e55-4c95-a4d3-426400f41c18"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1313fa0e-c239-47d9-af13-1a6a7fe35811"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25724387-6e90-4d65-905e-d103f1ecd203"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39f9ce0e-d97b-464d-be05-da486b5c5287"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7cfb23b9-6d6c-4a1a-9b62-cd7b4d71c26c"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c8a769d-de98-4e83-8c23-050374144175"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33078285-ee50-4825-9da0-acafde1fc5ef"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""923841bf-fcea-4d7d-88f1-51f5808511ab"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eea8370d-5811-46d6-a515-45bf62359d8f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Pirouette
        m_Pirouette = asset.FindActionMap("Pirouette", throwIfNotFound: true);
        m_Pirouette_Move = m_Pirouette.FindAction("Move", throwIfNotFound: true);
        m_Pirouette_PressX = m_Pirouette.FindAction("PressX", throwIfNotFound: true);
        m_Pirouette_PressY = m_Pirouette.FindAction("PressY", throwIfNotFound: true);
        m_Pirouette_PressA = m_Pirouette.FindAction("PressA", throwIfNotFound: true);
        m_Pirouette_PressB = m_Pirouette.FindAction("PressB", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Pirouette
    private readonly InputActionMap m_Pirouette;
    private IPirouetteActions m_PirouetteActionsCallbackInterface;
    private readonly InputAction m_Pirouette_Move;
    private readonly InputAction m_Pirouette_PressX;
    private readonly InputAction m_Pirouette_PressY;
    private readonly InputAction m_Pirouette_PressA;
    private readonly InputAction m_Pirouette_PressB;
    public struct PirouetteActions
    {
        private @MechanicsControls m_Wrapper;
        public PirouetteActions(@MechanicsControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Pirouette_Move;
        public InputAction @PressX => m_Wrapper.m_Pirouette_PressX;
        public InputAction @PressY => m_Wrapper.m_Pirouette_PressY;
        public InputAction @PressA => m_Wrapper.m_Pirouette_PressA;
        public InputAction @PressB => m_Wrapper.m_Pirouette_PressB;
        public InputActionMap Get() { return m_Wrapper.m_Pirouette; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PirouetteActions set) { return set.Get(); }
        public void SetCallbacks(IPirouetteActions instance)
        {
            if (m_Wrapper.m_PirouetteActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PirouetteActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PirouetteActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PirouetteActionsCallbackInterface.OnMove;
                @PressX.started -= m_Wrapper.m_PirouetteActionsCallbackInterface.OnPressX;
                @PressX.performed -= m_Wrapper.m_PirouetteActionsCallbackInterface.OnPressX;
                @PressX.canceled -= m_Wrapper.m_PirouetteActionsCallbackInterface.OnPressX;
                @PressY.started -= m_Wrapper.m_PirouetteActionsCallbackInterface.OnPressY;
                @PressY.performed -= m_Wrapper.m_PirouetteActionsCallbackInterface.OnPressY;
                @PressY.canceled -= m_Wrapper.m_PirouetteActionsCallbackInterface.OnPressY;
                @PressA.started -= m_Wrapper.m_PirouetteActionsCallbackInterface.OnPressA;
                @PressA.performed -= m_Wrapper.m_PirouetteActionsCallbackInterface.OnPressA;
                @PressA.canceled -= m_Wrapper.m_PirouetteActionsCallbackInterface.OnPressA;
                @PressB.started -= m_Wrapper.m_PirouetteActionsCallbackInterface.OnPressB;
                @PressB.performed -= m_Wrapper.m_PirouetteActionsCallbackInterface.OnPressB;
                @PressB.canceled -= m_Wrapper.m_PirouetteActionsCallbackInterface.OnPressB;
            }
            m_Wrapper.m_PirouetteActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @PressX.started += instance.OnPressX;
                @PressX.performed += instance.OnPressX;
                @PressX.canceled += instance.OnPressX;
                @PressY.started += instance.OnPressY;
                @PressY.performed += instance.OnPressY;
                @PressY.canceled += instance.OnPressY;
                @PressA.started += instance.OnPressA;
                @PressA.performed += instance.OnPressA;
                @PressA.canceled += instance.OnPressA;
                @PressB.started += instance.OnPressB;
                @PressB.performed += instance.OnPressB;
                @PressB.canceled += instance.OnPressB;
            }
        }
    }
    public PirouetteActions @Pirouette => new PirouetteActions(this);
    public interface IPirouetteActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnPressX(InputAction.CallbackContext context);
        void OnPressY(InputAction.CallbackContext context);
        void OnPressA(InputAction.CallbackContext context);
        void OnPressB(InputAction.CallbackContext context);
    }
}
